<?php

namespace Modules\Admin\Repositories;

use Modules\Core\Repositories\BaseCriteriaEloquent;
use Prettus\Repository\Contracts\CriteriaInterface;
use Prettus\Repository\Contracts\RepositoryInterface;

class PostsCriteria extends BaseCriteriaEloquent implements CriteriaInterface
{
    public function apply($model, RepositoryInterface $repository)
    {
        $builder = $model
            ->select(['posts.*', 'category_id', 'post_image'])
            ->leftJoin('post_categories', 'post_categories.post_id', '=', 'posts.id')
            ->leftJoin('post_images', 'post_images.post_id', '=', 'posts.id')
            ->where('post_type', 'post');
        return parent::apply($builder, $repository); // TODO: Change the autogenerated stub
    }
}
