<?php

namespace Modules\Admin\Repositories;


trait PostsCriteria
{
    public function apply($model)
    {
        $builder = $model
            ->select(['posts.*', 'category_id', 'post_image'])
            ->leftJoin('post_categories', 'post_categories.post_id', '=', 'posts.id')
            ->leftJoin('post_images', 'post_images.post_id', '=', 'posts.id')
            ->where('post_type', 'post');
        return $builder; // TODO: Change the autogenerated stub
    }
}
