<?php

namespace Modules\Admin\Repositories;

use Modules\Core\Repositories\BaseCriteriaEloquent;
use Prettus\Repository\Contracts\CriteriaInterface;
use Prettus\Repository\Contracts\RepositoryInterface;

class PostsCriteria extends BaseCriteriaEloquent implements CriteriaInterface
{
    public function apply($model, RepositoryInterface $repository)
    {
        $builder = $model->where('post_type', 'post');
        return parent::apply($builder, $repository); // TODO: Change the autogenerated stub
    }
}
