<?php

namespace Modules\Admin\Repositories;

use Illuminate\Support\Facades\DB;

trait RolesCriteria
{
    public function apply($model)
    {
        $builder = $model
            ->select([DB::raw('ROW_NUMBER() over(ORDER BY created_at desc) as st_index'), 'roles.*']);
        return $builder; // TODO: Change the autogenerated stub
    }
}
