<?php

namespace Modules\Admin\Repositories;

use Illuminate\Support\Facades\DB;

trait RolesCriteria
{
    public function apply($model)
    {
        $builder = $model->orderBy('role_rank')
                        ->orderBy('id');
        return $builder; // TODO: Change the autogenerated stub
    }
}
