<?php

namespace Modules\Admin\Repositories;

trait SlidesCriteria
{
    public function apply($model)
    {
        $builder = $model->where('advertise_type', 'slide');
        return $builder; // TODO: Change the autogenerated stub
    }
}
